# fly.toml app configuration file generated for cs-eslamhatem-backend-1i25nw on 2025-09-13T21:52:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cs-eslamhatem-backend-1i25nw'
primary_region = 'cdg'

[build]
  image = "registry.fly.io/cs-eslamhatem-backend-1i25nw:deployment-42c87c74ddc282b1bd79fac06114f2ba"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

   [http_service.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 400

  [http_service.http_options]
    max_request_body_size = 10737418240 # 10GB in bytes

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "uploads_data_100gb"
  destination = "/uploads"
